name: xesmf
channels:
  - conda-forge
dependencies:
  - codecov
  - dask
  - esmpy
  - numpy
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - scipy
  - pip:
      - git+https://github.com/pydata/xarray.git
