name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          python-version: 3.8
          environment-file: ci/environment-${{ matrix.python-version }}.yml
          activate-environment: xesmf
          auto-activate-base: false

      - name: Install xesmf
        run: |
          python -m pip install --no-deps -e .

      - name: Conda list information
        run: |
          conda env list
          conda list

      - name: Running tests
        run: |
          python -m pytest --cov=./ --cov-report=xml --verbose

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
